import "@/styles/globals.css";
import { instrument_sans, inter } from '@/styles/font';
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${instrument_sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
